apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathers
  labels:
    app: weathers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weathers
  template:
    metadata:
      labels:
        app: weathers
    spec:
      containers:
        - name: weathers
          image: impelfin/weathers
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://localhost:27017/weathers"
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
